/*===========================================================================
 * main.c -- Runs inference and reports cycle counts over the UART
 *===========================================================================
 *
 * This is the program that produces the project's headline numbers. It runs
 * the same model three ways -- baseline C, dot4 custom instruction, and the
 * MAC array -- and prints, for each:
 *
 *     total cycles, MAC-loop cycles, retired instructions, predicted class
 *     (and for the array: stall cycles and MAC utilisation)
 *
 * The MAC-loop fraction is what answers RQ1 and sets the Amdahl ceiling.
 * The stall fraction is what answers RQ3.
 *
 * WHICH VARIANTS ARE BUILT is controlled by -D flags from sw/Makefile, so
 * that a baseline measurement runs on hardware where the accelerator is
 * genuinely ABSENT rather than merely unused. Measuring "baseline" on a chip
 * that still contains the accelerator would overstate the baseline's area and
 * leakage and understate the accelerator's cost.
 *
 * NO printf(). Bare metal has no C library worth linking here, and printf
 * would pull in ~10 KB and a heap. The tiny integer formatter below is all we
 * need -- and its cycle cost is measured and excluded from the timed regions.
 *===========================================================================*/

#include <stdint.h>
#include "nn.h"
#include "perf.h"
#include "accel.h"

/* Generated by train/export_weights.py. Regenerate with `make weights`.
 * Not in git -- it is a build product, and a large one. */
#include "model_weights.h"

/*---------------------------------------------------------------------------
 * Minimal UART output
 *-------------------------------------------------------------------------*/
#define UART_DATA   (*(volatile uint32_t *)0x10000000u)
#define UART_STATUS (*(volatile uint32_t *)0x10000004u)

static void uart_putc(char c)
{
    /* Wait for the transmitter. Without this poll, characters written while
     * the shifter is busy are dropped and the output looks randomly
     * truncated -- which reads as "the program crashed halfway". */
    while (UART_STATUS & 1u) { }
    UART_DATA = (uint32_t)(uint8_t)c;
}

static void uart_puts(const char *s)
{
    while (*s) uart_putc(*s++);
}

/* Print a signed integer. Handles INT32_MIN correctly by accumulating in
 * negative space -- negating INT32_MIN overflows and is undefined behaviour,
 * a bug that hides until one unlucky value appears. */
static void uart_putd(int32_t v)
{
    char buf[12];
    int  i = 0;
    int  neg = (v < 0);

    if (v == 0) { uart_putc('0'); return; }
    while (v != 0) {
        int32_t digit = v % 10;
        if (digit < 0) digit = -digit;
        buf[i++] = (char)('0' + digit);
        v /= 10;
    }
    if (neg) uart_putc('-');
    while (i > 0) uart_putc(buf[--i]);
}

static void report(const char *label, int32_t value)
{
    uart_puts(label);
    uart_puts("=");
    uart_putd(value);
    uart_puts("\n");
}

/*---------------------------------------------------------------------------
 * Working buffers
 *-------------------------------------------------------------------------*/
/* Static, not stack: link.ld gives us only 4 KB of stack, and these are far
 * larger than that. Two buffers are enough because layers alternate between
 * them (ping-pong), which halves peak memory versus one buffer per layer.
 *
 * NOTE ON THE MISSING `scratch` ARRAY.
 * The layer kernels take a `scratch` pointer, as a hook for a future variant
 * that needs somewhere to land int32 accumulators. No current variant uses it
 * -- all three do `(void)scratch`. An earlier version of this file allocated
 * `int32_t scratch[MODEL_MAX_TENSOR]`, which at 4 bytes per element was
 * 32 KB: half the entire 64 KB RAM, reserved for something nothing read.
 * That pushed the image over budget and the ASSERT in link.ld caught it at
 * build time. We pass NULL instead. If a variant ever genuinely needs
 * scratch space, allocate exactly what that variant needs and re-check the
 * memory budget in docs/ARCHITECTURE.md section 8. */
static int8_t buf_a[MODEL_MAX_TENSOR];
static int8_t buf_b[MODEL_MAX_TENSOR];
#define SCRATCH_UNUSED ((int32_t *)0)

/* Declared in nn_dot4.c / nn_array.c. */
void nn_fc_dot4(const int8_t *in, const nn_fc_t *layer, int8_t *out);
void nn_conv2d_dot4(const int8_t *in, int32_t in_h, int32_t in_w,
                    const nn_conv_t *layer, int8_t *out,
                    int32_t *out_h, int32_t *out_w, int32_t *scratch);
void nn_fc_array(const int8_t *in, const nn_fc_t *layer, int8_t *out);
void nn_conv2d_array(const int8_t *in, int32_t in_h, int32_t in_w,
                     const nn_conv_t *layer, int8_t *out,
                     int32_t *out_h, int32_t *out_w, int32_t *scratch);

extern uint32_t g_accel_total_cycles, g_accel_total_stalls, g_accel_total_macs;
extern int32_t  g_accel_timeouts;

/* Which implementation to use, chosen at build time. */
typedef enum { VARIANT_BASELINE = 0, VARIANT_DOT4 = 1, VARIANT_ARRAY = 2 } variant_t;

/*---------------------------------------------------------------------------
 * run_inference -- one forward pass, timed
 *-------------------------------------------------------------------------*
 * Returns the predicted class. `mac_cycles` receives the cycles spent inside
 * the layer kernels (the part an accelerator can address), which is what the
 * Amdahl calculation needs.
 */
static int32_t run_inference(variant_t variant, const int8_t *input,
                             uint32_t *mac_cycles)
{
    int32_t h = MODEL_INPUT_H, w = MODEL_INPUT_W;
    int8_t *cur = buf_a, *nxt = buf_b;
    uint32_t t0, layer_cycles = 0;

    for (int32_t i = 0; i < MODEL_INPUT_CH * MODEL_INPUT_H * MODEL_INPUT_W; i++) {
        cur[i] = input[i];
    }

    for (int32_t li = 0; li < MODEL_NUM_LAYERS; li++) {
        const model_layer_t *L = &model_layers[li];

        switch (L->kind) {
        case LAYER_CONV: {
            int32_t oh, ow;
            t0 = perf_cycles();
            if (variant == VARIANT_DOT4)
                nn_conv2d_dot4(cur, h, w, &L->conv, nxt, &oh, &ow, SCRATCH_UNUSED);
            else if (variant == VARIANT_ARRAY)
                nn_conv2d_array(cur, h, w, &L->conv, nxt, &oh, &ow, SCRATCH_UNUSED);
            else
                nn_conv2d(cur, h, w, &L->conv, nxt, &oh, &ow, SCRATCH_UNUSED);
            layer_cycles += perf_cycles() - t0;
            h = oh; w = ow;
            { int8_t *tmp = cur; cur = nxt; nxt = tmp; }
            break;
        }
        case LAYER_RELU:
            /* Not timed as MAC work: ReLU is a comparison, not arithmetic an
             * accelerator would target. Counting it in the accelerable
             * fraction would inflate the Amdahl ceiling. */
            nn_relu(cur, L->n_elems, 0);
            break;

        case LAYER_MAXPOOL: {
            int32_t oh, ow;
            nn_maxpool2d(cur, L->pool_ch, h, w, L->pool_k, nxt, &oh, &ow);
            h = oh; w = ow;
            { int8_t *tmp = cur; cur = nxt; nxt = tmp; }
            break;
        }
        case LAYER_FC:
            t0 = perf_cycles();
            if (variant == VARIANT_DOT4)      nn_fc_dot4(cur, &L->fc, nxt);
            else if (variant == VARIANT_ARRAY) nn_fc_array(cur, &L->fc, nxt);
            else                               nn_fc(cur, &L->fc, nxt);
            layer_cycles += perf_cycles() - t0;
            { int8_t *tmp = cur; cur = nxt; nxt = tmp; }
            break;
        }
    }

    *mac_cycles = layer_cycles;
    return nn_argmax(cur, MODEL_NUM_CLASSES);
}

static void measure(const char *name, variant_t variant)
{
    uint32_t mac_cycles = 0;

    g_accel_total_cycles = 0;
    g_accel_total_stalls = 0;
    g_accel_total_macs   = 0;
    g_accel_timeouts     = 0;

    const uint32_t c0 = perf_cycles();
    const uint32_t i0 = perf_instret();

    const int32_t cls = run_inference(variant, model_test_input, &mac_cycles);

    const uint32_t total_cycles = perf_cycles() - c0;
    const uint32_t total_instr  = perf_instret() - i0;

    uart_puts("--- ");
    uart_puts(name);
    uart_puts(" ---\n");
    report("class",        cls);
    report("cycles_total", (int32_t)total_cycles);
    report("cycles_mac",   (int32_t)mac_cycles);
    report("instret",      (int32_t)total_instr);

    /* Permille rather than percent: integer division to one decimal place
     * without needing floating point. The analysis scripts divide by 10. */
    if (total_cycles > 0) {
        report("mac_permille",
               (int32_t)((uint64_t)mac_cycles * 1000u / total_cycles));
    }

    if (variant == VARIANT_ARRAY) {
        report("accel_cycles", (int32_t)g_accel_total_cycles);
        report("accel_stalls", (int32_t)g_accel_total_stalls);
        report("accel_macs",   (int32_t)g_accel_total_macs);
        if (g_accel_total_cycles > 0) {
            report("stall_permille",
                   (int32_t)((uint64_t)g_accel_total_stalls * 1000u
                             / g_accel_total_cycles));
        }
        /* A nonzero value here invalidates the run -- say so, do not let it
         * be mistaken for a fast result. */
        report("accel_timeouts", g_accel_timeouts);
    }
}

int main(void)
{
    uart_puts("\n=== riscv-inference-accelerator ===\n");
    uart_puts("model=" MODEL_NAME "\n");
    uart_puts("hash=" MODEL_HASH "\n");

    /* Report the measurement overhead so it can be subtracted, and so an
     * unexpectedly large value (a sign the counters are misconfigured) is
     * visible rather than silently biasing everything. */
    report("perf_overhead_cycles", (int32_t)perf_overhead());

#if defined(VARIANT_BUILD_BASELINE)
    measure("baseline", VARIANT_BASELINE);
#endif
#if defined(VARIANT_BUILD_DOT4)
    measure("dot4", VARIANT_DOT4);
#endif
#if defined(VARIANT_BUILD_ARRAY)
    measure("array", VARIANT_ARRAY);
#endif

    uart_puts("=== done ===\n");
    return 0;
}
