#!/usr/bin/env python3
"""Build, simulate and synthesise every configuration in the design space.

WHAT IT DOES
------------
For each cell of the full factorial in sweep/sweep_config.yaml:
  1. builds the RTL with those parameters (via iverilog -P overrides)
  2. runs a simulation to get cycle, stall and MAC counts
  3. optionally runs Vivado synthesis for LUT/FF/DSP/BRAM and timing
  4. records accuracy from the corresponding quantized model
  5. writes one tidy CSV row per (config, workload, replicate)

--dry-run skips Vivado, so the entire pipeline can be developed and tested
before anyone has Vivado installed or a board on the desk. That is the normal
mode until the hardware arrives.

ON REPLICATES
-------------
RTL simulation is deterministic: the same parameters give the same cycle
counts every time, so replicating the simulation measures nothing. Replicates
exist for the SYNTHESIS numbers, which are not deterministic -- Vivado's
placer and router are seeded and heuristic, so LUT counts and especially Fmax
vary between runs of the identical design.

Reporting a single Fmax as if it were exact would be wrong. run_sweep.py
therefore runs synthesis `replicates` times with different seeds and the
analysis reports mean and spread. In --dry-run mode replicates are collapsed
to 1 with a note, because duplicating deterministic rows would fake a
precision that does not exist.

Usage:
    python3 sweep/run_sweep.py --dry-run              # simulation only
    python3 sweep/run_sweep.py --dry-run --quick      # a small subset
    python3 sweep/run_sweep.py                        # full, needs Vivado
    python3 sweep/run_sweep.py --filter array_w=8     # one slice
"""

from __future__ import annotations

import argparse
import csv
import datetime
import itertools
import os
import re
import shutil
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, os.path.join(ROOT, "train"))

from config import load_config          # noqa: E402
from freeze import git_sha, config_hash  # noqa: E402

RTL_FILES = [
    "dot4_pcpi.v", "mac_unit.v", "mac_array.v", "weight_buffer.v",
    "activation_buffer.v", "accel_ctrl.v", "accel_top.v", "perf_counter.v",
    "requantize.v", "uart_tx.v", "soc_top.v",
]

CSV_COLUMNS = [
    "array_w", "array_h", "wbuf_depth", "abuf_depth", "precision",
    "workload", "replicate",
    "cycles_total", "cycles_active", "cycles_stall", "macs_done",
    "utilisation", "stall_fraction", "sim_ok",
    "luts", "ffs", "dsps", "brams", "fmax_mhz", "wns_ns",
    "timing_met", "synth_ok",
    "accuracy", "accuracy_is_synthetic",
    "energy_per_inference_uj", "energy_source",
    "git_sha", "timestamp_utc", "iverilog_version", "vivado_version",
    "config_sha256", "seed",
]

# The sweep testbench. Kept here rather than in sim/ because it is generated
# per configuration and is not something anyone edits by hand.
SWEEP_TB = r"""
`timescale 1ns/1ps
// Auto-generated by sweep/run_sweep.py.
// Drives one accelerator configuration through a fixed synthetic workload and
// prints the performance counters. The workload SHAPE (M, N, K) is what
// varies between the two workloads; the data values do not affect cycle
// counts, so they are left at defaults.
module tb_sweep;
  localparam H = ARRAY_H_P, W = ARRAY_W_P;
  reg clk = 0, resetn = 0, start = 0;
  wire busy, done, arr_clr, arr_en, stall;
  wire wre, are, rp;
  wire [15:0] wa, aa, ti, tj;
  always #5 clk = ~clk;

  accel_ctrl #(.ARRAY_H(H), .ARRAY_W(W),
               .WBUF_DEPTH(WBUF_P), .ABUF_DEPTH(ABUF_P),
               .PRECISION(PREC_P)) dut (
    .clk(clk), .resetn(resetn), .start(start),
    .dim_m(DIM_M_P), .dim_n(DIM_N_P), .dim_k(DIM_K_P),
    .busy(busy), .done(done), .arr_clr(arr_clr), .arr_en(arr_en),
    .wbuf_rd_en(wre), .wbuf_rd_addr(wa),
    .abuf_rd_en(are), .abuf_rd_addr(aa),
    .res_push(rp), .res_tile_i(ti), .res_tile_j(tj), .stall_o(stall));

  integer cycles = 0, active = 0, stalls = 0, macs = 0, guard = 0;
  always @(posedge clk) begin
    if (busy) begin
      cycles = cycles + 1;
      if (arr_en) begin active = active + 1; macs = macs + H*W; end
      if (stall)  stalls = stalls + 1;
    end
    guard = guard + 1;
    if (guard > 20000000) begin
      $display("RESULT sim_ok=0 reason=timeout");
      $finish;
    end
  end

  initial begin
    @(posedge clk); resetn <= 1; @(posedge clk);
    start <= 1; @(posedge clk); start <= 0;
    wait(done);
    @(posedge clk);
    $display("RESULT sim_ok=1 cycles=%0d active=%0d stalls=%0d macs=%0d",
             cycles, active, stalls, macs);
    $finish;
  end
endmodule
"""


def tool_version(cmd: list[str], pattern: str = r"([\d.]+)") -> str:
    try:
        out = subprocess.run(cmd, capture_output=True, text=True, timeout=20)
        text = (out.stdout or "") + (out.stderr or "")
        m = re.search(pattern, text)
        return m.group(1) if m else text.strip().splitlines()[0][:40]
    except Exception:
        return ""


def workload_dims(workload: str) -> tuple[int, int, int]:
    """The matrix shape each workload presents to the accelerator.

    Derived from the frozen configs' largest layer, because that layer
    dominates the cycle count and is the one worth optimising.

      workload_a: the FC layer, 1024 -> 4, so M=1 N=4 K=256 (K in 4-byte words)
      workload_b: the largest FC, 32 -> 128, so M=1 N=128 K=8
    """
    if workload == "workload_a":
        return 1, 4, 256
    return 1, 128, 8


def run_simulation(array_h: int, array_w: int, wbuf: int, abuf: int,
                   precision: int, workload: str, timeout: int,
                   workdir: str) -> dict:
    """Compile and run one configuration. Returns the measured counters."""
    m, n, k = workload_dims(workload)

    tb = (SWEEP_TB
          .replace("ARRAY_H_P", str(array_h))
          .replace("ARRAY_W_P", str(array_w))
          .replace("WBUF_P", str(wbuf))
          .replace("ABUF_P", str(abuf))
          .replace("PREC_P", str(precision))
          .replace("DIM_M_P", f"16'd{m}")
          .replace("DIM_N_P", f"16'd{n}")
          .replace("DIM_K_P", f"16'd{k}"))

    tb_path = os.path.join(workdir, "tb_sweep.v")
    with open(tb_path, "w") as fh:
        fh.write(tb)

    vvp = os.path.join(workdir, "tb_sweep.vvp")
    compile_cmd = ["iverilog", "-g2005", "-I", os.path.join(ROOT, "rtl"),
                   "-o", vvp, tb_path,
                   os.path.join(ROOT, "rtl", "accel_ctrl.v")]
    res = subprocess.run(compile_cmd, capture_output=True, text=True)
    if res.returncode != 0:
        return {"sim_ok": False, "error": res.stderr[:400]}

    try:
        res = subprocess.run(["vvp", vvp], capture_output=True, text=True,
                             timeout=timeout)
    except subprocess.TimeoutExpired:
        return {"sim_ok": False, "error": "timeout"}

    for line in res.stdout.splitlines():
        if line.startswith("RESULT"):
            fields = dict(kv.split("=", 1) for kv in line.split()[1:]
                          if "=" in kv)
            if fields.get("sim_ok") != "1":
                return {"sim_ok": False,
                        "error": fields.get("reason", "unknown")}
            cycles = int(fields["cycles"])
            macs = int(fields["macs"])
            peak = array_h * array_w * max(cycles, 1)
            return {
                "sim_ok": True,
                "cycles_total": cycles,
                "cycles_active": int(fields["active"]),
                "cycles_stall": int(fields["stalls"]),
                "macs_done": macs,
                "utilisation": round(macs / peak, 6),
                "stall_fraction": round(int(fields["stalls"]) / max(cycles, 1), 6),
            }
    return {"sim_ok": False, "error": "no RESULT line in simulator output"}


def run_synthesis(array_h: int, array_w: int, wbuf: int, abuf: int,
                  precision: int, part: str, target_mhz: float,
                  seed: int, workdir: str) -> dict:
    """Run Vivado in non-project mode and parse the utilisation/timing reports."""
    vivado = shutil.which("vivado")
    if vivado is None:
        return {"synth_ok": False, "error": "vivado not found"}

    outdir = os.path.join(workdir, f"synth_{array_w}_{wbuf}_{precision}_{seed}")
    os.makedirs(outdir, exist_ok=True)

    cmd = [
        vivado, "-mode", "batch", "-nojournal", "-nolog",
        "-source", os.path.join(HERE, "vivado", "build.tcl"),
        "-tclargs",
        f"-part={part}", f"-array_h={array_h}", f"-array_w={array_w}",
        f"-wbuf={wbuf}", f"-abuf={abuf}", f"-precision={precision}",
        f"-period={1000.0/target_mhz:.3f}", f"-seed={seed}",
        f"-outdir={outdir}", f"-root={ROOT}",
    ]
    try:
        res = subprocess.run(cmd, capture_output=True, text=True, timeout=3600)
    except subprocess.TimeoutExpired:
        return {"synth_ok": False, "error": "vivado timeout"}

    if res.returncode != 0:
        return {"synth_ok": False, "error": res.stdout[-400:]}

    summary = os.path.join(outdir, "summary.txt")
    if not os.path.exists(summary):
        return {"synth_ok": False, "error": "no summary.txt produced"}

    vals: dict = {}
    with open(summary) as fh:
        for line in fh:
            if "=" in line:
                k, v = line.strip().split("=", 1)
                vals[k.strip()] = v.strip()

    try:
        wns = float(vals.get("WNS", "nan"))
        period = 1000.0 / target_mhz
        return {
            "synth_ok": True,
            "luts": int(float(vals.get("LUT", 0))),
            "ffs": int(float(vals.get("FF", 0))),
            "dsps": int(float(vals.get("DSP", 0))),
            "brams": float(vals.get("BRAM", 0)),
            "wns_ns": wns,
            # Fmax from slack: achieved period = target - slack.
            "fmax_mhz": round(1000.0 / (period - wns), 2) if period > wns else 0.0,
            "timing_met": wns >= 0,
        }
    except (ValueError, ZeroDivisionError) as exc:
        return {"synth_ok": False, "error": f"could not parse reports: {exc}"}


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--config", default=os.path.join(HERE, "sweep_config.yaml"))
    ap.add_argument("--dry-run", action="store_true",
                    help="simulation only; skip Vivado synthesis")
    ap.add_argument("--quick", action="store_true",
                    help="a small subset, for checking the pipeline works")
    ap.add_argument("--out", default=None)
    ap.add_argument("--filter", action="append", default=[],
                    help="restrict a factor, e.g. --filter array_w=8")
    args = ap.parse_args()

    cfg = load_config(args.config)
    factors = cfg["factors"]

    array_ws = factors["array_w"]
    wbufs = factors["wbuf_depth"]
    precisions = factors["precision"]
    workloads = factors["workload"]

    if args.quick:
        array_ws, wbufs, precisions = [1, 8], [0, 1024], [8]
        workloads = workloads[:1]
        print("QUICK MODE: a subset only, for pipeline checking.")

    for f in args.filter:
        key, _, val = f.partition("=")
        if key == "array_w":     array_ws = [int(val)]
        elif key == "wbuf_depth": wbufs = [int(val)]
        elif key == "precision":  precisions = [int(val)]
        elif key == "workload":   workloads = [val]
        else:
            ap.error(f"unknown filter key '{key}'")

    replicates = cfg.get("replicates", 1)
    if args.dry_run and replicates > 1:
        print(f"NOTE: --dry-run, so replicates collapsed {replicates} -> 1.")
        print("      RTL simulation is deterministic; repeating it would")
        print("      manufacture an appearance of precision that is not real.")
        print("      Replicates exist for Vivado's non-deterministic placer.")
        replicates = 1

    out_csv = args.out or os.path.join(ROOT, cfg["output"]["csv"])
    os.makedirs(os.path.dirname(out_csv), exist_ok=True)

    if shutil.which("iverilog") is None:
        print("ERROR: iverilog not found -- nothing can be simulated.\n"
              "  macOS: brew install icarus-verilog\n"
              "  Ubuntu: sudo apt-get install iverilog", file=sys.stderr)
        return 127

    iv_ver = tool_version(["iverilog", "-V"], r"Icarus Verilog version ([\d.]+)")
    viv_ver = "" if args.dry_run else tool_version(["vivado", "-version"],
                                                   r"Vivado v([\d.]+)")
    sha = git_sha()

    # Frozen config hashes, so each row can be traced to an exact model.
    wl_hashes, wl_synth = {}, {}
    for wl in workloads:
        p = os.path.join(ROOT, "train", "config", f"{wl}.yaml")
        if os.path.exists(p):
            wc = load_config(p)
            wl_hashes[wl] = config_hash(wc)
            golden = os.path.join(ROOT, "sim", "golden", f"{wc['name']}.json")
            if os.path.exists(golden):
                import json
                with open(golden) as fh:
                    wl_synth[wl] = bool(json.load(fh).get("synthetic", False))

    cells = list(itertools.product(array_ws, wbufs, precisions, workloads))
    total = len(cells) * replicates
    print(f"Sweeping {len(cells)} configurations x {replicates} replicate(s) "
          f"= {total} runs")
    print(f"  synthesis: {'DISABLED (--dry-run)' if args.dry_run else 'enabled'}")
    print(f"  output:    {out_csv}")
    print()

    rows, n_done, n_fail = [], 0, 0
    with tempfile.TemporaryDirectory(prefix="sweep_") as workdir:
        for (aw, wb, prec, wl) in cells:
            ah = aw if cfg.get("array_h_follows_w", True) else aw
            for rep in range(replicates):
                n_done += 1
                sim = run_simulation(ah, aw, wb, wb, prec, wl,
                                     cfg["simulation"]["timeout_seconds"],
                                     workdir)
                syn = ({"synth_ok": False} if args.dry_run else
                       run_synthesis(ah, aw, wb, wb, prec,
                                     cfg["synthesis"]["part"],
                                     cfg["synthesis"]["target_clock_mhz"],
                                     rep, workdir))

                if not sim.get("sim_ok"):
                    n_fail += 1
                    print(f"  [{n_done}/{total}] FAIL {aw}x{ah} wbuf={wb} "
                          f"p={prec} {wl}: {sim.get('error','?')}")
                else:
                    print(f"  [{n_done}/{total}] {aw}x{ah} wbuf={wb:4d} "
                          f"p={prec} {wl:10s} "
                          f"cycles={sim['cycles_total']:6d} "
                          f"stalls={sim['cycles_stall']:6d} "
                          f"util={sim['utilisation']:.3f}")

                rows.append({
                    "array_w": aw, "array_h": ah,
                    "wbuf_depth": wb, "abuf_depth": wb,
                    "precision": prec, "workload": wl, "replicate": rep,
                    "cycles_total": sim.get("cycles_total", ""),
                    "cycles_active": sim.get("cycles_active", ""),
                    "cycles_stall": sim.get("cycles_stall", ""),
                    "macs_done": sim.get("macs_done", ""),
                    "utilisation": sim.get("utilisation", ""),
                    "stall_fraction": sim.get("stall_fraction", ""),
                    "sim_ok": sim.get("sim_ok", False),
                    "luts": syn.get("luts", ""), "ffs": syn.get("ffs", ""),
                    "dsps": syn.get("dsps", ""), "brams": syn.get("brams", ""),
                    "fmax_mhz": syn.get("fmax_mhz", ""),
                    "wns_ns": syn.get("wns_ns", ""),
                    "timing_met": syn.get("timing_met", ""),
                    "synth_ok": syn.get("synth_ok", False),
                    # Accuracy is filled in by the quantization pipeline, not
                    # measured here. Left blank rather than zero so it can
                    # never be mistaken for "0% accurate".
                    "accuracy": "",
                    "accuracy_is_synthetic": wl_synth.get(wl, ""),
                    # Energy needs the PPK2, which does not exist yet.
                    "energy_per_inference_uj": "TBD_MEASURED",
                    "energy_source": "TBD_MEASURED",
                    "git_sha": sha,
                    "timestamp_utc": datetime.datetime.now(
                        datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
                    "iverilog_version": iv_ver,
                    "vivado_version": viv_ver,
                    "config_sha256": wl_hashes.get(wl, ""),
                    "seed": rep,
                })

    with open(out_csv, "w", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=CSV_COLUMNS)
        w.writeheader()
        w.writerows(rows)

    print()
    print(f"Wrote {out_csv}: {len(rows)} rows, {n_fail} failed")
    if n_fail:
        print("  Rows with sim_ok=False must be EXCLUDED from analysis, not")
        print("  treated as zeros. See sweep/results/SCHEMA.md.")
    print()
    print("  energy_per_inference_uj is TBD_MEASURED for every row: the Power")
    print("  Profiler Kit II has not been purchased, and this project does not")
    print("  substitute estimates for measurements.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
